FROM golang:1.16-alpine AS builder

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
ENV GO111MODULE=on
# ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

COPY . .
RUN set -ex &&\
    apk add --no-progress --no-cache \
    gcc \
    musl-dev
RUN go build -tags musl -o main .

FROM scratch AS runtime
COPY --from=builder /go/src/main /
EXPOSE 8080
EXPOSE 50051
ENTRYPOINT ["./main", "all"]
